---
test_reuse_full: '/Users/usiusi/Documents/Repositories/test-attribute-extractor/data/output/analyse/full'
craft_gt: '/Users/usiusi/Documents/Repositories/matching-server/prefrect_matcher/craft_gt/'
atm_gt: '/Users/usiusi/Documents/Repositories/matching-server/prefrect_matcher/atm_gt/'
